services:
  php:
    image: php:8.3-fpm
    user: ${UID:-1000}:${GID:-1000}
    volumes:
      - .:/usr/share/nginx/html
    working_dir: /usr/share/nginx/html
    networks:
      - app-network

  nginx:
    build:
      context: ./.docker/nginx
      args:
        SERVER_NAME: ${SERVER_NAME}
        ENVIRONMENT: ${ENVIRONMENT}
    volumes:
      - .:/usr/share/nginx/html
      - certs:/etc/letsencrypt
      - certs:/etc/ssl/private
      - certs:/etc/ssl/certs
      - ./.docker/nginx/default.conf.template:/etc/nginx/conf.d/default.conf.template
    working_dir: /usr/share/nginx/html
    ports:
      - "443:443"
    networks:
      - app-network
    env_file:
      - .env
    depends_on:
      - certbot
    entrypoint: "/bin/sh /usr/share/nginx/wait-for-certbot.sh"

  certbot:
    build:
      context: ./.docker/certbot
      args:
        EMAIL: ${EMAIL}
        SERVER_NAME: ${SERVER_NAME}
    volumes:
      - certs:/etc/letsencrypt
      - certs:/etc/ssl/private
      - certs:/etc/ssl/certs
    ports:
      - "80:80"
    env_file:
      - .env
    entrypoint: "/bin/sh /usr/local/bin/entrypoint.sh"

  composer:
    image: composer:2
    user: ${UID:-1000}:${GID:-1000}
    volumes:
      - .:/app
    tty: true

networks:
  app-network:
    driver: bridge

volumes:
  certs:
