services:
  apache:
    build:
      context: .docker/apache
      dockerfile: Dockerfile
      args:
        UID: ${UID:-1000}
        GID: ${GID:-1000}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.apache.rule=Host(`${SERVER_NAME}`)"
      - "traefik.http.routers.apache.entrypoints=websecure"
      - "traefik.http.routers.apache.tls=true"
    volumes:
      - .:/var/www/html
    env_file:
      - .env
    networks:
      - proxy-network
      - default

  database:
    image: mariadb:lts
    environment:
      MYSQL_ROOT_PASSWORD: $DB_ROOT_PASSWORD
      MYSQL_USER: $DB_USERNAME
      MYSQL_PASSWORD: $DB_PASSWORD
      MYSQL_DATABASE: $DB_DATABASE
    ports:
      - '3306:3306'
    volumes:
      - 'mysql_data:/var/lib/mysql'

networks:
  proxy-network:
    external: true

volumes:
  mysql_data:
